name: GoogleTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc libcunit1 libcunit1-dev

    - name: Configure CMake
      run: |
        mkdir -p tests/build
        cd tests/build
        cmake ..

    - name: Build project
      run: |
        cd tests/build
        cmake --build .

    - name: Run tests
      run: |
        cd tests/build
        ctest --output-on-failure
