name: GoogleTests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up GCC 20
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-20 g++-20

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake g++ make

    - name: Install GoogleTest
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake . 
        sudo make 
        sudo make install

    - name: Configure CMake
      run: |
        mkdir -p tests/build
        cd tests/build
        cmake ..

    - name: Build project
      run: |
        cd tests/build
        cmake --build .

    - name: Run tests
      run: |
        cd tests/build
        ctest --verbose --output-on-failure
